[build]
builder = "Nixpacks"
output = "."

[phases.setup]
nixPkgs = ['nodejs_18', 'php81', 'php81Packages.composer']
aptPkgs = ['libpng-dev', 'libonig-dev', 'libxml2-dev']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'npm install',
  'npm run build',
  'php artisan optimize:clear',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port ${PORT}'
