[phases.setup]
nixPkgs = ['nodejs_18', 'php81', 'php81Packages.composer']
aptPkgs = ['libpng-dev', 'libonig-dev', 'libxml2-dev']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'npm install',
  'npm run build'
]

[start]
cmd = 'php artisan config:clear && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=${PORT}'
